### ISSUE TITLE
启动start_trace.py提示错误could not load module 'QBDI/frida-qbdi.js'

### ISSUE THREAD

**Issue by shmilyaxy** [lasting-yang/frida-qbdi-tracer#2]
紧修改了warp_vm_run.js文件：
`/**
 * warp_vm_run的函数定义不要修改
 * @param {*} vm_run_func   会调用qbdi的vm.call
 * @param {*} log_file_path 日志文件的路径
 */
export default function warp_vm_run(vm_run_func, log_file_path) {
    // let baselibEncryptor = Module.findBaseAddress("libEncryptor.so");
    // let addr_2BD8 = baselibEncryptor.add(0x2BD8);
    // let str0 = "0123456789abcdef";
    // let arg0 = Memory.allocUtf8String(str0);
    // let ret_len = str0.length + 0x76;

    // let arg1 = Memory.alloc(ret_len);
    // let arg2 = Memory.alloc(16);
    // arg2.writeU64(ret_len);
    let baselibEncryptor = Module.findBaseAddress("libnative-lib.so");
    let addr_FF30 = baselibEncryptor.add(0xFF30);
    let str0 = "e4Uyx8KwqBtrjXcOhLVs0xWjeGp3kaF3HoQc";
    let arg0 = Memory.allocUtf8String(str0);

    /**
     * addr_2BD8 是主动调用函数的地址
     * [arg0, str0.length, arg1, arg2] 是参数
     * log_file_path 日志文件的路径
     */
    // let ret = vm_run_func(addr_2BD8, [arg0, str0.length, arg1, arg2], log_file_path)
    let ret = vm_run_func(addr_FF30, [arg0], log_file_path)

    console.log(ret, "\r\n", hexdump(ret, {
        length: ret_len
    }))
}`
运行python start_trace.py提示如下错误：
`C:\Users\shmily\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py

> build
> frida-compile agent.js -o _agent.js -c -S

Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in <module>
    script = session.create_script(read_agent_js_source())
  File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 9, in read_agent_js_source
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 68: illegal multibyte sequence`
修改start_trace.py代码如下：
`def read_agent_js_source():
    with open("_agent.js", "r", encoding="utf-8") as f:
        return f.read()`
运行提示如下错误：
`C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py

> build
> frida-compile agent.js -o _agent.js -c -S

Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in <module>
    script = session.create_script(read_agent_js_source())
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 262, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.InvalidArgumentError: could not load module 'QBDI/frida-qbdi.js'`
github下载frida-qbdi-tracer文件并运行，路径应该没有问题，其他文件并未修改，不知道问什么提示此错误，请各位大佬解答

**Comment by JansZeng** [comment]
python start_trace.py

> build
> frida-compile agent.js -o _agent.js -c -S

Traceback (most recent call last):
  File "start_trace.py", line 42, in <module>
    script = session.create_script(read_agent_js_source())
  File "/Users/jans/Documents/program/python/dy/venv/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Users/jans/Documents/program/python/dy/venv/lib/python3.7/site-packages/frida/core.py", line 262, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.InvalidArgumentError: could not load module 'QBDI/frida-qbdi.js'

I have the same question, Look forward to your reply

**Comment by FBLeee** [comment]
> 紧修改了warp_vm_run.js文件： `/**
> 
> * warp_vm_run的函数定义不要修改
> * @param {*} vm_run_func   会调用qbdi的vm.call
> * @param {*} log_file_path 日志文件的路径
>   */
>   export default function warp_vm_run(vm_run_func, log_file_path) {
>   // let baselibEncryptor = Module.findBaseAddress("libEncryptor.so");
>   // let addr_2BD8 = baselibEncryptor.add(0x2BD8);
>   // let str0 = "0123456789abcdef";
>   // let arg0 = Memory.allocUtf8String(str0);
>   // let ret_len = str0.length + 0x76;
>   // let arg1 = Memory.alloc(ret_len);
>   // let arg2 = Memory.alloc(16);
>   // arg2.writeU64(ret_len);
>   let baselibEncryptor = Module.findBaseAddress("libnative-lib.so");
>   let addr_FF30 = baselibEncryptor.add(0xFF30);
>   let str0 = "e4Uyx8KwqBtrjXcOhLVs0xWjeGp3kaF3HoQc";
>   let arg0 = Memory.allocUtf8String(str0);
>   /**
>   
>   * addr_2BD8 是主动调用函数的地址
>   * [arg0, str0.length, arg1, arg2] 是参数
>   * log_file_path 日志文件的路径
>     */
>     // let ret = vm_run_func(addr_2BD8, [arg0, str0.length, arg1, arg2], log_file_path)
>     let ret = vm_run_func(addr_FF30, [arg0], log_file_path)
>   
>   console.log(ret, "\r\n", hexdump(ret, {
>   length: ret_len
>   }))
>   }`运行python start_trace.py提示如下错误：`C:\Users\shmily\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py
> 
> > build
> > frida-compile agent.js -o _agent.js -c -S
> 
> Traceback (most recent call last): File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in script = session.create_script(read_agent_js_source()) File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 9, in read_agent_js_source return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 68: illegal multibyte sequence`修改start_trace.py代码如下：`def read_agent_js_source(): with open("_agent.js", "r", encoding="utf-8") as f: return f.read()`运行提示如下错误：`C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py
> 
> > build
> > frida-compile agent.js -o _agent.js -c -S
> 
> Traceback (most recent call last): File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in script = session.create_script(read_agent_js_source()) File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 26, in wrapper return f(*args, **kwargs) File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 262, in create_script return Script(self._impl.create_script(*args, **kwargs)) frida.InvalidArgumentError: could not load module 'QBDI/frida-qbdi.js'` github下载frida-qbdi-tracer文件并运行，路径应该没有问题，其他文件并未修改，不知道问什么提示此错误，请各位大佬解答

I have the same question, Look forward to your reply +1

**Comment by FBLeee** [comment]
> 紧修改了warp_vm_run.js文件： `/**
> 
> * warp_vm_run的函数定义不要修改
> * @param {*} vm_run_func   会调用qbdi的vm.call
> * @param {*} log_file_path 日志文件的路径
>   */
>   export default function warp_vm_run(vm_run_func, log_file_path) {
>   // let baselibEncryptor = Module.findBaseAddress("libEncryptor.so");
>   // let addr_2BD8 = baselibEncryptor.add(0x2BD8);
>   // let str0 = "0123456789abcdef";
>   // let arg0 = Memory.allocUtf8String(str0);
>   // let ret_len = str0.length + 0x76;
>   // let arg1 = Memory.alloc(ret_len);
>   // let arg2 = Memory.alloc(16);
>   // arg2.writeU64(ret_len);
>   let baselibEncryptor = Module.findBaseAddress("libnative-lib.so");
>   let addr_FF30 = baselibEncryptor.add(0xFF30);
>   let str0 = "e4Uyx8KwqBtrjXcOhLVs0xWjeGp3kaF3HoQc";
>   let arg0 = Memory.allocUtf8String(str0);
>   /**
>   
>   * addr_2BD8 是主动调用函数的地址
>   * [arg0, str0.length, arg1, arg2] 是参数
>   * log_file_path 日志文件的路径
>     */
>     // let ret = vm_run_func(addr_2BD8, [arg0, str0.length, arg1, arg2], log_file_path)
>     let ret = vm_run_func(addr_FF30, [arg0], log_file_path)
>   
>   console.log(ret, "\r\n", hexdump(ret, {
>   length: ret_len
>   }))
>   }`运行python start_trace.py提示如下错误：`C:\Users\shmily\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py
> 
> > build
> > frida-compile agent.js -o _agent.js -c -S
> 
> Traceback (most recent call last): File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in script = session.create_script(read_agent_js_source()) File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 9, in read_agent_js_source return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 68: illegal multibyte sequence`修改start_trace.py代码如下：`def read_agent_js_source(): with open("_agent.js", "r", encoding="utf-8") as f: return f.read()`运行提示如下错误：`C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py
> 
> > build
> > frida-compile agent.js -o _agent.js -c -S
> 
> Traceback (most recent call last): File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in script = session.create_script(read_agent_js_source()) File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 26, in wrapper return f(*args, **kwargs) File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 262, in create_script return Script(self._impl.create_script(*args, **kwargs)) frida.InvalidArgumentError: could not load module 'QBDI/frida-qbdi.js'` github下载frida-qbdi-tracer文件并运行，路径应该没有问题，其他文件并未修改，不知道问什么提示此错误，请各位大佬解答

找到问题原因了，os库路径问题，因为这个start_trace.py代码中有在windows中的路径，又有在android系统中的路径，所以如果在windows下运行，需要把start_trace.py改成下面即可（或者全程在linux系统下，yang应该就是在linux系统下的）：
```
import frida
import os
import sys



def read_agent_js_source():
    with open("_agent.js", "r", encoding="utf-8") as f:
        return f.read()

def on_message(message, data):
    print(message)
    pass

def build_agent_js():
    _agent_path = "_agent.js"
    if os.path.exists(_agent_path):
        os.remove(_agent_path)
    os.system("npm run build")
    
    if not os.path.exists(_agent_path):
        raise RuntimeError('frida-compile agent.js error')

def remove_agent_js():
    _agent_path = "_agent.js"
    if os.path.exists(_agent_path):
        os.remove(_agent_path)

if __name__ == "__main__":
    build_agent_js()

    curdir = os.path.dirname(os.path.abspath(sys.argv[0]))
    libQBDI = os.path.abspath(os.path.join(curdir, "QBDI/libQBDI.so"))
    
    #print("libQBDI:",libQBDI)
    frida_qbdi_js = os.path.abspath(os.path.join(curdir, "QBDI/frida-qbdi.js"))

    device: frida.core.Device = frida.get_usb_device()
    #print("device:",device)
    #print("device.get_frontmost_application():",device.get_frontmost_application())
    pid = device.get_frontmost_application().pid
    

    
    session: frida.core.Session = device.attach(pid)

    script = session.create_script(read_agent_js_source())

    script.on('message', on_message)
    script.load()

    #-------------------------下面路径时linux，上面路径时windows

    #关键！！！！
    filesdir = f'{script.exports.getfilesdir()}/'
    #print("filesdir:",filesdir)

    target_so_path = (os.path.join(filesdir, "libQBDI.so"))
    #print("target_so_path:",target_so_path)
    if not script.exports.checksoexist(target_so_path):
        with open(libQBDI, "rb") as f:
            so_buffer = f.read()
            script.exports.writelibqbdiso(target_so_path,  list(so_buffer))

    log_path = os.path.join(filesdir, "trace.log")
    #print("log_path:",log_path)
    script.exports.vmrun(log_path)


    remove_agent_js()
```

**Comment by shmilyaxy** [comment]
> > 紧修改了warp_vm_run.js文件： `/**
> > 
> > * warp_vm_run的函数定义不要修改
> > * @param {*} vm_run_func   会调用qbdi的vm.call
> > * @param {*} log_file_path 日志文件的路径
> >   _/
> >   export default function warp_vm_run(vm_run_func, log_file_path) {
> >   // let baselibEncryptor = Module.findBaseAddress("libEncryptor.so");
> >   // let addr_2BD8 = baselibEncryptor.add(0x2BD8);
> >   // let str0 = "0123456789abcdef";
> >   // let arg0 = Memory.allocUtf8String(str0);
> >   // let ret_len = str0.length + 0x76;
> >   // let arg1 = Memory.alloc(ret_len);
> >   // let arg2 = Memory.alloc(16);
> >   // arg2.writeU64(ret_len);
> >   let baselibEncryptor = Module.findBaseAddress("libnative-lib.so");
> >   let addr_FF30 = baselibEncryptor.add(0xFF30);
> >   let str0 = "e4Uyx8KwqBtrjXcOhLVs0xWjeGp3kaF3HoQc";
> >   let arg0 = Memory.allocUtf8String(str0);
> >   /_*
> >   
> >   * addr_2BD8 是主动调用函数的地址
> >   * [arg0, str0.length, arg1, arg2] 是参数
> >   * log_file_path 日志文件的路径
> >     */
> >     // let ret = vm_run_func(addr_2BD8, [arg0, str0.length, arg1, arg2], log_file_path)
> >     let ret = vm_run_func(addr_FF30, [arg0], log_file_path)
> >   
> >   console.log(ret, "\r\n", hexdump(ret, {
> >   length: ret_len
> >   }))
> >   }`运行python start_trace.py提示如下错误：`C:\Users\shmily\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py
> > 
> > > build
> > > frida-compile agent.js -o _agent.js -c -S
> > 
> > 
> > Traceback (most recent call last): File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in script = session.create_script(read_agent_js_source()) File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 9, in read_agent_js_source return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 68: illegal multibyte sequence`修改start_trace.py代码如下：`def read_agent_js_source(): with open("_agent.js", "r", encoding="utf-8") as f: return f.read()`运行提示如下错误：`C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master>python start_trace.py
> > > build
> > > frida-compile agent.js -o _agent.js -c -S
> > 
> > 
> > Traceback (most recent call last): File "C:\Users\xxxx\Desktop\frida-qbdi-tracer-master\frida-qbdi-tracer-master\start_trace.py", line 40, in script = session.create_script(read_agent_js_source()) File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 26, in wrapper return f(*args, **kwargs) File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 262, in create_script return Script(self._impl.create_script(*args, **kwargs)) frida.InvalidArgumentError: could not load module 'QBDI/frida-qbdi.js'` github下载frida-qbdi-tracer文件并运行，路径应该没有问题，其他文件并未修改，不知道问什么提示此错误，请各位大佬解答
> 
> 找到问题原因了，os库路径问题，因为这个start_trace.py代码中有在windows中的路径，又有在android系统中的路径，所以如果在windows下运行，需要把start_trace.py改成下面即可（或者全程在linux系统下，yang应该就是在linux系统下的）：
> 
> ```
> import frida
> import os
> import sys
> 
> 
> 
> def read_agent_js_source():
>     with open("_agent.js", "r", encoding="utf-8") as f:
>         return f.read()
> 
> def on_message(message, data):
>     print(message)
>     pass
> 
> def build_agent_js():
>     _agent_path = "_agent.js"
>     if os.path.exists(_agent_path):
>         os.remove(_agent_path)
>     os.system("npm run build")
>     
>     if not os.path.exists(_agent_path):
>         raise RuntimeError('frida-compile agent.js error')
> 
> def remove_agent_js():
>     _agent_path = "_agent.js"
>     if os.path.exists(_agent_path):
>         os.remove(_agent_path)
> 
> if __name__ == "__main__":
>     build_agent_js()
> 
>     curdir = os.path.dirname(os.path.abspath(sys.argv[0]))
>     libQBDI = os.path.abspath(os.path.join(curdir, "QBDI/libQBDI.so"))
>     
>     #print("libQBDI:",libQBDI)
>     frida_qbdi_js = os.path.abspath(os.path.join(curdir, "QBDI/frida-qbdi.js"))
> 
>     device: frida.core.Device = frida.get_usb_device()
>     #print("device:",device)
>     #print("device.get_frontmost_application():",device.get_frontmost_application())
>     pid = device.get_frontmost_application().pid
>     
> 
>     
>     session: frida.core.Session = device.attach(pid)
> 
>     script = session.create_script(read_agent_js_source())
> 
>     script.on('message', on_message)
>     script.load()
> 
>     #-------------------------下面路径时linux，上面路径时windows
> 
>     #关键！！！！
>     filesdir = f'{script.exports.getfilesdir()}/'
>     #print("filesdir:",filesdir)
> 
>     target_so_path = (os.path.join(filesdir, "libQBDI.so"))
>     #print("target_so_path:",target_so_path)
>     if not script.exports.checksoexist(target_so_path):
>         with open(libQBDI, "rb") as f:
>             so_buffer = f.read()
>             script.exports.writelibqbdiso(target_so_path,  list(so_buffer))
> 
>     log_path = os.path.join(filesdir, "trace.log")
>     #print("log_path:",log_path)
>     script.exports.vmrun(log_path)
> 
> 
>     remove_agent_js()
> ```

我尝试了，还是不行，问题好像出在script = session.create_script(read_agent_js_source()) 这句代码，在加载js脚本的时候，无法找加载模块：could not load module 'QBDI/frida-qbdi.js'。不知是否哪里还需要改动呢？
