### ISSUE TITLE
frida.core.RPCException

### ISSUE THREAD

**Issue by anylayer** [lasting-yang/frida-qbdi-tracer#6]
> build
> frida-compile agent.js -o _agent.js -c -S

start vmrun
Traceback (most recent call last):
  File "/root/Desktop/frida-qbdi-tracer/start_trace.py", line 53, in <module>
    script.exports_sync.vmrun(log_path)
  File "/root/.pyenv/versions/3.9.8/lib/python3.9/site-packages/frida/core.py", line 179, in method
    return script._rpc_request("call", js_name, args, **kwargs)
  File "/root/.pyenv/versions/3.9.8/lib/python3.9/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.8/lib/python3.9/site-packages/frida/core.py", line 491, in _rpc_request
    raise result.error
frida.core.RPCException: Error: Expected an array
    at toJni (frida/node_modules/frida-java-bridge/lib/types.js:292)
    at toJni (frida/node_modules/frida-java-bridge/lib/types.js:300)
    at array (frida/node_modules/frida-java-bridge/lib/class-factory.js:197)
    at array (frida/node_modules/frida-java-bridge/index.js:273)
    at a (/warp_vm_run.js:1)
    at <anonymous> (/agent.js:1)
    at vmrun (/agent.js:1)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)

**Comment by vmtest888** [comment]
```
> build
> frida-compile agent.js -o _agent.js -c -S

start vmrun
log_file_path:  /data/user/0/com.testjava.jack.pingan2/files\trace.log
start vm.call
Traceback (most recent call last):
  File "D:\work\source\frida-qbdi-tracer\start_trace.py", line 54, in <module>
    script.exports_sync.vmrun(log_path)
  File "D:\Program Files\Python311\Lib\site-packages\frida\core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\frida\core.py", line 497, in _rpc_request
    raise result.error
frida.core.RPCException: EvalError: Execution failed
    at <anonymous> (/QBDI/frida-qbdi.js:12)
    at apply (native)
    at call (/QBDI/frida-qbdi.js:12)
    at c (/agent.js:1)
    at e (/warp_vm_run.js:1)
    at <anonymous> (/agent.js:1)
    at vmrun (/agent.js:1)
    at call (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:11)
    at o (frida/runtime/message-dispatcher.js:23)
```
类似错误
